# .air.toml
[build]
  cmd = "go run cmd/main.go"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = true
  delay = 1000
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"
