FROM golang:1.24-alpine

WORKDIR /app

# Install air for hot reload and swag for API documentation
RUN go install github.com/air-verse/air@v1.62.0
RUN go install github.com/swaggo/swag/cmd/swag@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Run air for hot reload
CMD ["air", "-c", ".air.toml"] 