basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a backend for a Slack clone with chat, audio/video calling.
  title: Slack Clone API
  version: "1.0"
paths: {}
swagger: "2.0"
